server:
  port: 8080

management:
  context-path: /system
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/otecteng/springcloud-workshop-tw.git
          searchPaths: '/tw-workshop-config-data/{application}/{profile}'
